conversation/urls.py
from django.urls import path

from . import views

app_name = 'conversation'

urlpatterns = [
    path('', views.inbox, name='inbox'),
    path('<int:pk>/', views.detail, name='detail'),
    path('new/<int:item_pk>/', views.new_conversation, name='new'),
    path('delete/<int:pk>/', views.delete, name='delete'),
    path('edit/<int:pk>/', views.edit, name='edit'),
]

core/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name='login'),
]

cursach/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls')),
    path('items/', include('item.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('inbox/', include('conversation.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/urls.py
from django.urls import path

from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='index'),
    path('history/', views.history, name='history'),
    path('wishlist/', views.wishlist, name='wishlist'),
    path('wishlist/add/<int:item_id>/', views.add_to_wishlist, name='add_to_wishlist'),
    path('wishlist/remove/<int:item_id>/', views.remove_from_wishlist, name='remove_from_wishlist'),
    path('wishlist/remove2/<int:item_id>/', views.remove_from_wishlist2, name='remove_from_wishlist2'),
    path('user/<int:user_id>/', views.user_profile, name='user_profile'),
    path('change_user_data/', views.change_user_data, name='change_user_data'),

]

item/urls.py
from django.urls import path

from . import views

app_name = 'item'

urlpatterns = [
    path('', views.items, name='items'),
    path('new/', views.new, name='new'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),
    path('<int:item_id>/complaint/', views.complaint, name='complaint'),
    path('complaint/', views.complaint_list, name='complaint_list'),
]

core/models.py
from django.db import models

# Create your models here.

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Введіть ім`я користувача',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Введіть пароль',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')
    
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Введіть ім`я користувача',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'Введіть ел пошту',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Введіть пароль',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Повторіть пароль',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

core/views.py
from django.shortcuts import render, redirect

from item.models import Category, Item, Complaint

from .forms import SignupForm

def index(request):
    items = Item.objects.filter(is_sold=False).order_by('-created_at')[0:6]
    categories = Category.objects.all()

    return render(request, 'core/index.html', {
        'categories': categories,
        'items': items,
    })


def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)

        if form.is_valid():
            form.save()

            return redirect('/login/')
    else:
        form = SignupForm()

    return render(request, 'core/signup.html', {
        'form': form
    })
    

core/templates/core/base.html
<!doctype html>

<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>
        <script src="https://cdn.tailwindcss.com"></script>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

        <title>{% block title %}{% endblock %} | Дошка оголошень</title>
    </head>

    <body>
        <nav class="py-4 px-6 bg-white border-b border-gray-200">
            <div class="flex justify-between items-center">
                <a href="/" class="text-xl font-semibold">Дошка оголошень для волонтерів</a>
        
                <div class="spac">
                    {% if request.user.is_superuser %}
                    <a href="{% url 'item:complaint_list' %}" class="btn btn-block btn-lg btn-primary">Скарги</a>
                    {% endif %}
        
                    <a href="{% url 'item:items' %}" class="btn btn-block btn-lg btn-primary">Пошук</a>
        
                    {% if request.user.is_authenticated %}
                        <a href="{% url 'conversation:inbox' %}" class="btn btn-block btn-lg btn-primary">Чат</a>
                        <a href="{% url 'dashboard:index' %}" class="btn btn-block btn-lg btn-secondary">Профіль</a>
                    {% else %}
                        <a href="{% url 'core:signup' %}" class="btn btn-block btn-lg btn-primary">Реєстрація</a>
                        <a href="{% url 'core:login' %}" class="btn btn-block btn-lg btn-secondary">Логін</a>
                    {% endif %}
                </div>
            </div>
        </nav>

        <div class="px-6 py-6">
            {% block content %}
            {% endblock %}
        </div>

        <style>
            @media (max-width: 768px) {
                .space-x-6 {
                    display: flex;
                    flex-direction: column;
                    align-items: center;
                }
        
                .spac a {
                    margin-bottom: 0.5rem;
                    width: 100%;
                }
            }
            
        </style>
    </body>
</html>

core/templates/core/index.html
{% extends 'core/base.html' %}

{% block title %}Головна{% endblock %}

{% block content %}
    <div class="container mt-6">
        <h2 class="mb-4 text-2xl text-center">Категорії на сайті</h2>

        <div class="row row-cols-1 row-cols-md-3 g-4">
            {% for category in categories|dictsort:"id" %}
                <div class="col">
                    <a href="{% url 'item:items' %}?query={{ query }}&category={{ category.id }}" class="text-decoration-none">
                        <div class="p-4 bg-light rounded-bottom shadow-sm ">
                            <h2 class="text-2xl">{{ category.name }}</h2>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div> 

    <div class="container mt-6">
        <h2 class="mb-4 text-2xl text-center">Нові оголошення</h2>

        <div class="row row-cols-1 row-cols-md-3 g-4">
            {% for item in items %}
                <div class="col">
                    <a href="{% url 'item:detail' item.id %}" class="text-decoration-none">
                        <div class="overflow-hidden rounded-top aspect-ratio-4/3 bg-light">
                            <img src="{{ item.image.url }}" class="object-fit w-100 h-100">
                        </div>

                        <div class="p-4 bg-light rounded-bottom shadow-sm">
                            <h2 class="text-2xl">{{ item.name }}</h2>
                            <p class="text-gray-500">Ціна: {{ item.price }}</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

core/templates/core/login.html
{% extends 'core/base.html' %}

{% block title %}Логін{% endblock %}

{% block content %}
<div class="container my-6">
    <div class="card p-4 bg-light rounded shadow">
        <h1 class="mb-4 text-3xl text-center">Логін</h1>

        <form method="post" action=".">
            {% csrf_token %}

            <div class="mb-3">
                <label for="{{ form.username.id_for_label }}" class="form-label">Ім'я користувача</label>
                {{ form.username }}
            </div>

            <div class="mb-3">
                <label for="{{ form.password.id_for_label }}" class="form-label">Пароль</label>
                {{ form.password }}
            </div>

            {% if form.errors or form.non_field_errors %}
                <div class="mb-3 p-4 bg-danger text-white rounded">
                    {% for field in form %}
                        {{ field.errors }}
                    {% endfor %}

                    {{ form.non_field_errors }}
                </div>
            {% endif %}

            <button type="submit" class="btn btn-primary bg-primary">Підтвердити</button>
        </form>
    </div>
</div>
{% endblock %}

core/templates/core/signup.html
{% extends 'core/base.html' %}

{% block title %}Реєстрація{% endblock %}

{% block content %}
<div class="container my-6">
    <div class="card p-4 bg-light rounded shadow">
        <h1 class="mb-4 text-3xl text-center">Реєстрація</h1>

        <form method="post" action=".">
            {% csrf_token %}

            <div class="mb-3">
                <label for="{{ form.username.id_for_label }}" class="form-label">Ім'я користувача</label>
                {{ form.username }}
            </div>

            <div class="mb-3">
                <label for="{{ form.email.id_for_label }}" class="form-label">Електронна пошта</label>
                {{ form.email }}
            </div>

            <div class="mb-3">
                <label for="{{ form.password1.id_for_label }}" class="form-label">Пароль</label>
                {{ form.password1 }}
            </div>

            <div class="mb-3">
                <label for="{{ form.password2.id_for_label }}" class="form-label">Підтвердження пароля</label>
                {{ form.password2 }}
            </div>

            {% if form.errors or form.non_field_errors %}
                <div class="mb-3 p-4 bg-danger text-white rounded">
                    {% for field in form %}
                        {{ field.errors }}
                    {% endfor %}

                    {{ form.non_field_errors }}
                </div>
            {% endif %}

            <button type="submit" class="btn btn-primary bg-primary">Підтвердити</button>
        </form>
    </div>
</div>
{% endblock %}