conversation/urls.py
from django.urls import path

from . import views

app_name = 'conversation'

urlpatterns = [
    path('', views.inbox, name='inbox'),
    path('<int:pk>/', views.detail, name='detail'),
    path('new/<int:item_pk>/', views.new_conversation, name='new'),
    path('delete/<int:pk>/', views.delete, name='delete'),
    path('edit/<int:pk>/', views.edit, name='edit'),
]

core/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name='login'),
]

cursach/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls')),
    path('items/', include('item.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('inbox/', include('conversation.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/urls.py
from django.urls import path

from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='index'),
    path('history/', views.history, name='history'),
    path('wishlist/', views.wishlist, name='wishlist'),
    path('wishlist/add/<int:item_id>/', views.add_to_wishlist, name='add_to_wishlist'),
    path('wishlist/remove/<int:item_id>/', views.remove_from_wishlist, name='remove_from_wishlist'),
    path('wishlist/remove2/<int:item_id>/', views.remove_from_wishlist2, name='remove_from_wishlist2'),
    path('user/<int:user_id>/', views.user_profile, name='user_profile'),
    path('change_user_data/', views.change_user_data, name='change_user_data'),

]

item/urls.py
from django.urls import path

from . import views

app_name = 'item'

urlpatterns = [
    path('', views.items, name='items'),
    path('new/', views.new, name='new'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),
    path('<int:item_id>/complaint/', views.complaint, name='complaint'),
    path('complaint/', views.complaint_list, name='complaint_list'),
]

item/models.py
from django.contrib.auth.models import User
from django.db import models

class Category(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        ordering = ('name',)
        verbose_name_plural = 'Categories'
    
    def __str__(self):
        return self.name

class Region(models.Model):
    name = models.CharField(max_length=55)

    class Meta:
        ordering = ('name',)
        verbose_name_plural = 'Regions'
    
    def __str__(self):
        return self.name

class Item(models.Model):
    
    category = models.ForeignKey(Category, related_name='items', on_delete=models.CASCADE)
    name = models.CharField(max_length=75)
    description = models.TextField(blank=True, null=True)
    price = models.FloatField()
    region = models.ForeignKey(Region, related_name='items', on_delete=models.CASCADE)
    image = models.ImageField(upload_to='item_images', blank=True, null=True)
    is_sold = models.BooleanField(default=False)
    created_by = models.ForeignKey(User, related_name='items', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.name
    
class Complaint(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='complaints')
    post = models.ForeignKey(Item, on_delete=models.CASCADE, related_name='complaints')
    text = models.TextField()
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Complaint #{self.id} - {self.post.name}"

item/forms.py
from django import forms

from .models import Item, Complaint

INPUT_CLASSES = 'w-full py-4 px-6 rounded-xl border'


class NewItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('category', 'name', 'description', 'region', 'price', 'image',)
        labels = {
            'name': ('Назва'),
            'description': ('Опис'),
            'region': ('Регіон'),
            'price': ('Ціна'),
            'image': ('Зображення'),
            'category': ('Категорія'),
        }
        widgets = {
            'category': forms.Select(attrs={
                'class': INPUT_CLASSES
            }),
            'name': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'description': forms.Textarea(attrs={
                'class': INPUT_CLASSES
            }),
            'region': forms.Select(attrs={
                'class': INPUT_CLASSES
            }),
            'price': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'image': forms.FileInput(attrs={
                'class': INPUT_CLASSES
            })
        }
        
    def clean_price(self):
        price = self.cleaned_data['price']
        if price < 0:
            raise forms.ValidationError("Ціна не може бути від'ємною")
        return price
    def clean_image(self):
        image = self.cleaned_data['image']
        if not image:
            raise forms.ValidationError("Завантаження зображення є обов'язковим")
        return image    

class EditItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('name', 'description', 'region', 'price', 'image', 'is_sold')
        labels = {
            'name': ('Назва'),
            'description': ('Опис'),
            'region': ('Регіон'),
            'price': ('Ціна'),
            'image': ('Зображення'),
            'is_sold': ('Деактивувати'),
        }
        widgets = {
            'name': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'description': forms.Textarea(attrs={
                'class': INPUT_CLASSES
            }),
            'region': forms.Select(attrs={
                'class': INPUT_CLASSES
            }),
            'price': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'image': forms.FileInput(attrs={
                'class': INPUT_CLASSES
            })
        }
        
    def clean_price(self):
        price = self.cleaned_data['price']
        if price < 0:
            raise forms.ValidationError("Ціна не може бути від'ємною")
        return price
    def clean_image(self):
        image = self.cleaned_data['image']
        if not image:
            raise forms.ValidationError("Завантаження зображення є обов'язковим")
        return image
        
class ComplaintForm(forms.ModelForm):
    class Meta:
        model = Complaint
        fields = ('text',)
        widgets = {
            'text': forms.Textarea(attrs={
                'class': INPUT_CLASSES
            })
        }

        

item/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .enviroment import REGIONS
from .forms import NewItemForm, EditItemForm, ComplaintForm
from .models import Category, Item, Complaint, Region
from django.db.models.functions import Lower
from dashboard.models import History, Wishlist

def items(request):
    query = request.GET.get('query', '')
    category_id = request.GET.get('category')
    if category_id:
        category_id = int(category_id)
    else:
        category_id = 0
    region_id = request.GET.get('region')
    if region_id:
        region_id = int(region_id)
    else:
        region_id = 0
    min_price = request.GET.get('min_price', 0)
    max_price = request.GET.get('max_price', float('inf'))

    categories = Category.objects.all()
    regions = Region.objects.all()
    all_items = Item.objects.filter(is_sold=False).order_by('-created_at')

    if category_id is not "0" and category_id:
        all_items = all_items.filter(category_id=int(category_id))
    
    if query:
        all_items = all_items.filter(
        Q(name__icontains=query) | Q(description__icontains=query) | Q(name__icontains=query[1:]) | Q(description__icontains=query[1:])
    )
        
    if region_id is not "0" and region_id:
        all_items = all_items.filter(region_id=int(region_id))

    if min_price and max_price:
        min_price, max_price = float(min_price), float(max_price)
        if max_price > 0 and min_price > max_price:
            min_price, max_price = max_price, min_price
        all_items = all_items.filter(price__gte=min_price, price__lte=max_price)
    elif min_price:
        all_items = all_items.filter(price__gte=min_price)

    paginator = Paginator(all_items, 9)
    
    page = request.GET.get('page', 1)

    try:
        items = paginator.page(page)
    except PageNotAnInteger:
        items = paginator.page(1)
    except EmptyPage:
        items = paginator.page(paginator.num_pages)

    return render(request, 'item/items.html', {
        'items': items,
        'query': query,
        'categories': categories,
        'category_id': int(category_id),
        'region_id': int(region_id),
        'regions': regions, 
        'min_price': min_price,
        'max_price': max_price,
    })
    
    

def detail(request, pk):
    item = get_object_or_404(Item, pk=pk)
    related_items = Item.objects.filter(category=item.category, is_sold=False).exclude(pk=pk)[0:3]

    in_wishlist = False
    if request.user.is_authenticated:
        history_record = History.objects.filter(user=request.user, item=item).first()
        
        if history_record:
            history_record.delete()
        History.objects.create(user=request.user, item=item)
        in_wishlist = Wishlist.objects.filter(user=request.user, item=item).exists()

    return render(request, 'item/detail.html', {
        'item': item,
        'related_items': related_items,
        'in_wishlist': in_wishlist
    })

@login_required    
def complaint(request, item_id):
    item = get_object_or_404(Item, pk=item_id)

    if request.method == 'POST':
        form = ComplaintForm(request.POST)

        if form.is_valid():
            complaint = form.save(commit=False)
            complaint.author = request.user
            complaint.post = item
            complaint.save()

            return redirect('item:detail', pk=item.id)
    else:
        form = ComplaintForm()

    return render(request, 'item/form.html', {'item': item, 'form': form})

@login_required
def new(request):
    if request.method == 'POST':
        form = NewItemForm(request.POST, request.FILES)

        if form.is_valid():
            item = form.save(commit=False)
            item.created_by = request.user
            item.save()

            return redirect('item:detail', pk=item.id)
    else:
        form = NewItemForm()

    return render(request, 'item/form.html', {
        'form': form,
        'title': 'Створення оголошення',
    })

@login_required
def edit(request, pk):
    item = get_object_or_404(Item, pk=pk, created_by=request.user)

    if request.method == 'POST':
        form = EditItemForm(request.POST, request.FILES, instance=item)

        if form.is_valid():
            form.save()

            return redirect('item:detail', pk=item.id)
    else:
        form = EditItemForm(instance=item)

    return render(request, 'item/form.html', {
        'form': form,
        'title': 'Редагування',
    })

@login_required
def delete(request, pk):
    item = get_object_or_404(Item, pk=pk)
    complaints = Complaint.objects.filter(post=pk)
    complaints.delete()
    item.delete()
    return redirect('dashboard:index')

def complaint_list(request):
    complaints = Complaint.objects.all()
    return render(request, 'item/complaint.html', {'complaints': complaints})

item/templates/item/complaint.html
{% extends 'core/base.html' %}

{% block title %}Список скарг{% endblock %}

{% block content %}
  <div class="container mx-auto my-8">
    <h2 class="text-2xl font-semibold mb-4">Список скарг</h2>

    <div class="overflow-x-auto">
      <table class="min-w-full bg-white border border-gray-300">
        <thead>
          <tr>
            <th class="py-2 px-4 border-b text-left">ID</th>
            <th class="py-2 px-4 border-b text-left">Автор</th>
            <th class="py-2 px-4 border-b text-left">Оголошення</th>
            <th class="py-2 px-4 border-b text-left">Зміст скарги</th>
            <th class="py-2 px-4 border-b text-left">Дата</th>
          </tr>
        </thead>
        <tbody>
          {% for complaint in complaints %}
            <tr>
              <td class="py-2 px-4 border-b text-left">{{ complaint.id }}</td>
              <td class="py-2 px-4 border-b text-left">{{ complaint.author.username }}</td>
              <td class="py-2 px-4 border-b text-left">
                <a href="{% url 'item:detail' complaint.post.id %}" class="text-blue-500 hover:underline">{{ complaint.post.name }}</a>
              </td>
              <td class="py-2 px-4 border-b text-left">{{ complaint.text }}</td>
              <td class="py-2 px-4 border-b text-left">{{ complaint.date }}</td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
{% endblock %}

item/templates/item/detail.html
{% extends 'core/base.html' %}

{% block title %}{{ item.name }}{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-7">
        <img src="{{ item.image.url }}" class="img-fluid rounded-xl w-100 h-auto">
    </div>    

    <div class="col-md-5 p-4 bg-gray-100 rounded-xl">
        <h1 class="mb-4 text-3xl">{{ item.name }}</h1>
        <p class="text-gray-500"><strong>Ціна: </strong>{{ item.price }}</p>
        <p class="text-gray-500"><strong>Продавець: </strong>{{ item.created_by.username }}</p>
        {% if request.user != item.created_by %}
            <a href="{% url 'dashboard:user_profile' item.created_by.id %}" class="btn btn-primary mt-2">Переглянути усі оголошення {{ item.created_by.username }}</a>
        {% endif %}

        {% if item.region %}
            <p class="text-gray-700">
                <strong class="text-gray-500">Регіон:</strong>
                {{ item.region }}
            </p>
        {% endif %}
        
        {% if item.category %}
            <p class="text-gray-700">
                <strong class="text-gray-500">Категорія:</strong>
                {{ item.category.name }}
            </p>
        {% endif %}

        {% if item.description %}
            <p class="text-gray-700">
                <strong class="text-gray-500">Опис:</strong>
                {{ item.description }}
            </p>
        {% endif %}

        {% if request.user == item.created_by %}
            <div class="mt-4 p-4 bg-white rounded-xl">
                <p>Дії з вашим оголошенням</p>

                <a href="{% url 'item:edit' item.id %}" class="btn btn-primary mt-2">Редагувати</a>
                <a href="{% url 'item:delete' item.id %}" class="btn btn-danger mt-2">Видалити</a>
                <div class="text-left mt-2">
                    <a href="#" onclick="window.history.back()" class="btn btn-secondary">Повернутися назад</a>
                </div>
            </div>
        {% else %}
            <a href="{% url 'conversation:new' item.id %}" class="btn btn-primary mt-2">Написати продавцю</a>
            {% if in_wishlist %}
                <a href="{% url 'dashboard:remove_from_wishlist' item.id %}" class="btn btn-danger mt-2">Видалити з списку обраних</a>
            {% else %}
                <a href="{% url 'dashboard:add_to_wishlist' item.id %}" class="btn btn-primary mt-2">Додати до списку обраних ♡</a>
            {% endif %}
            <a href="{% url 'item:complaint' item.id %}" class="btn btn-danger mt-2">Поскаржитися</a>
            
            {% if request.user.is_superuser %}
                <a href="{% url 'item:delete' item.id %}" class="btn btn-danger mt-2">Видалити</a>
            {% endif %}
            <div class="text-left mt-2">
                <a href="#" onclick="window.history.back()" class="btn btn-secondary">Повернутися назад</a>
            </div>
        {% endif %}
    </div>
</div>

<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class="mb-4 text-2xl text-center">Вас може зацікавити</h2>

    <div class="row row-cols-1 row-cols-md-3 g-4">
        {% for item in related_items %}
            <div class="col">
                <a href="{% url 'item:detail' item.id %}" class="text-decoration-none">
                    <div class="overflow-hidden rounded-top aspect-ratio-4/3 bg-light">
                        <img src="{{ item.image.url }}" class="object-fit w-100 h-100">
                    </div>

                    <div class="p-4 bg-light rounded-bottom shadow-sm">
                        <h2 class="text-2xl">{{ item.name }}</h2>
                        <p class="text-gray-500">Ціна: {{ item.price }}</p>
                    </div>
                </a>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

item/templates/item/form.html
{% extends 'core/base.html' %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
<h1 class="mb-6 text-3xl">{{ title }}</h1>

<form method="post" action="." enctype="multipart/form-data">
    {% csrf_token %}

    <div class="space-y-4">
        {{ form.as_p }}
    </div>

    {% if form.errors or form.non_field_errors %}
        <div class="mb-3 p-6 bg-red-100 rounded-xl">
            {% for field in form %}
                {{ field.errors }}
            {% endfor %}

            {{ form.non_field_errors }}
        </div>
    {% endif %}

    <button class="btn btn-primary bg-primary mt-2">Підтвердити</button>
    <button href="#" onclick="window.history.back()" class="btn btn-danger mt-2">Скасувати</button>
</form>
{% endblock %}

item/templates/item/items.html
{% extends 'core/base.html' %}

{% block title %}Оголошення{% endblock %}

{% block content %}
    <div class="container-fluid py-5 bg-light">
        <div class="row">
            <div class="col-md-3">
                <form method="get" action="{% url 'item:items' %}">
                    <div class="mb-3">
                        <input name="query" class="form-control py-3" type="text" value="{{ query }}" placeholder="Що шукаєте?">
                    </div>

                <hr class="my-4"> 

                <p class="font-weight-bold">Категорії</p>

                <select name="category" class="form-control">
                    <option value="0" {% if not category_id %}selected{% endif %}>Усі категорії</option>
                    {% for category in categories|dictsort:"id" %}
                        <option value="{{ category.id }}" {% if category.id == category_id %}selected{% endif %}>{{ category.name }}</option>
                    {% endfor %}
                </select>
                <hr class="my-4">

                <p class="font-weight-bold">Регіон</p>
                <select name="region" class="form-control">
                    <option value="" {% if not region_id %}selected{% endif %}>Вся Україна</option>
                    {% for r in regions|dictsort:"id" %}
                        <option value="{{ r.id }}" {% if r.id == region_id %}selected{% endif %}>{{ r.name }}</option>
                    {% endfor %}
                </select>

                <hr class="my-4">
                
                <p class="font-weight-bold">Діапазон цін</p>
                <div class="mb-3">
                    <label for="min_price">Мінімальна ціна:</label>
                    <input type="number" name="min_price" min="0" id="min_price" value="{{ min_price }}" class="form-control">
                </div>

                <div class="mb-3">
                    <label for="max_price">Максимальна ціна:</label>
                    <input type="number" name="max_price" min="0" id="max_price" value="{{ max_price }}" class="form-control">
                </div>

                <hr class="my-4">

                <button class="btn btn-primary btn-block">Фільтрувати</button>
                </form>
                <ul class="list-unstyled">
                    <li><a href="{% url 'item:items' %}" class="mt-2 btn btn-warning btn-block mb-2">Скинути фільтр</a></li>
                </ul>
            </div>

            <div class="col-md-9">
                <div class="row row-cols-1 row-cols-md-3 g-4">
                    {% for item in items %}
                        <div class="col">
                            <a href="{% url 'item:detail' item.id %}" class="text-decoration-none">
                                <div class="overflow-hidden rounded-top aspect-ratio-4/3 bg-light">
                                    <img src="{{ item.image.url }}" class="object-fit w-100 h-100">
                                </div>

                                <div class="p-4 bg-light rounded-bottom shadow-sm">
                                    <h2 class="text-2xl">{{ item.name }}</h2>
                                    <p class="text-gray-500">Ціна: {{ item.price }}</p>
                                </div>
                            </a>
                        </div>
                    {% endfor %}
                </div>
                <div class="container my-4">
                    <div class="row justify-content-center">
                        <nav aria-label="Page navigation">
                            <ul class="pagination justify-content-center">
                                {% if items.has_previous %}
                                    <li class="page-item">
                                        <a class="page-link" href="?page=1" aria-label="First">
                                            <span aria-hidden="true">&laquo;&laquo;</span>
                                        </a>
                                    </li>
                                    <li class="page-item">
                                        <a class="page-link" href="?page={{ items.previous_page_number }}" aria-label="Previous">
                                            <span aria-hidden="true">&laquo;</span>
                                        </a>
                                    </li>
                                {% endif %}
                
                                <li class="page-item disabled">
                                    <span class="page-link">Сторінка {{ items.number }} з {{ items.paginator.num_pages }}</span>
                                </li>
                
                                {% if items.has_next %}
                                    <li class="page-item">
                                        <a class="page-link" href="?page={{ items.next_page_number }}" aria-label="Next">
                                            <span aria-hidden="true">&raquo;</span>
                                        </a>
                                    </li>
                                    <li class="page-item">
                                        <a class="page-link" href="?page={{ items.paginator.num_pages }}" aria-label="Last">
                                            <span aria-hidden="true">&raquo;&raquo;</span>
                                        </a>
                                    </li>
                                {% endif %}
                            </ul>
                        </nav>
                    </div>
                </div>
                
            </div>
        </div>
    </div>
{% endblock %}