core/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name='login'),
]

cursach/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls')),
    path('items/', include('item.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('inbox/', include('conversation.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/urls.py
from django.urls import path

from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='index'),
    path('history/', views.history, name='history'),
    path('wishlist/', views.wishlist, name='wishlist'),
    path('wishlist/add/<int:item_id>/', views.add_to_wishlist, name='add_to_wishlist'),
    path('wishlist/remove/<int:item_id>/', views.remove_from_wishlist, name='remove_from_wishlist'),
    path('wishlist/remove2/<int:item_id>/', views.remove_from_wishlist2, name='remove_from_wishlist2'),
    path('user/<int:user_id>/', views.user_profile, name='user_profile'),
    path('change_user_data/', views.change_user_data, name='change_user_data'),

]

item/urls.py
from django.urls import path

from . import views

app_name = 'item'

urlpatterns = [
    path('', views.items, name='items'),
    path('new/', views.new, name='new'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),
    path('<int:item_id>/complaint/', views.complaint, name='complaint'),
    path('complaint/', views.complaint_list, name='complaint_list'),
]

dashboard/models.py
from django.contrib.auth.models import User
from item.models import Item
from django.db import models

class History(models.Model):
    user = models.ForeignKey(User, related_name='history_items', on_delete=models.CASCADE)
    item = models.ForeignKey(Item, related_name='history_items', on_delete=models.CASCADE)

class Wishlist(models.Model):
    user = models.ForeignKey(User, related_name='wish_items', on_delete=models.CASCADE)
    item = models.ForeignKey(Item, related_name='wish_items', on_delete=models.CASCADE)

dashboard/views.py
from pyexpat.errors import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout as auth_logout
from django.shortcuts import get_object_or_404, render, redirect
from dashboard.models import History, Wishlist
from item.models import Item
from django.contrib.auth.models import User
from django.contrib import messages


@login_required
def index(request):
    items = Item.objects.filter(created_by=request.user)

    if request.method == 'POST':
        auth_logout(request)
        return redirect('core:index')  

    return render(request, 'dashboard/index.html', {
        'items': items,
    })

@login_required
def history(request):
    items = History.objects.filter(user=request.user).order_by('id').reverse()

    return render(request, 'dashboard/history.html', {
        'items': items,
    })

@login_required
def wishlist(request):
    items = Wishlist.objects.filter(user=request.user).order_by('id').reverse()

    return render(request, 'dashboard/wishlist.html', {
        'items': items,
    })

@login_required
def add_to_wishlist(request, item_id):
    item = get_object_or_404(Item, id=item_id)
    Wishlist.objects.get_or_create(user=request.user, item=item)
    return redirect('item:detail', pk=item_id)

@login_required
def remove_from_wishlist(request, item_id):
    item = get_object_or_404(Item, id=item_id)
    Wishlist.objects.filter(user=request.user, item=item).delete()
    return redirect('item:detail', pk=item_id)

@login_required
def remove_from_wishlist2(request, item_id):
    item = get_object_or_404(Item, id=item_id)
    Wishlist.objects.filter(user=request.user, item=item).delete()
    items = Wishlist.objects.filter(user=request.user).order_by('id').reverse()

    return render(request, 'dashboard/wishlist.html', {
        'items': items,
    })

@login_required
def user_profile(request, user_id):
    user = get_object_or_404(User, id=user_id)
    items = Item.objects.filter(created_by=user).order_by('-created_at')

    return render(request, 'dashboard/user_profile.html', {
        'user_profile': user,
        'items': items,
    })

@login_required
def change_user_data(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        email = request.POST.get('email')

        # Перевірка, чи імейл або нікнейм вже використовується
        if User.objects.exclude(id=request.user.id).filter(email=email).exists() or User.objects.exclude(id=request.user.id).filter(username=username).exists():
            error_message = 'Цей email або нікнейм вже використовується.'
            return render(request, 'dashboard/change_user_data.html', {'error_message': error_message})

        # Оновлення даних користувача
        user = request.user
        user.username = username
        user.email = email
        user.save()

        messages.success(request, 'Особисті дані оновлені')
        return redirect('dashboard:index')

    return render(request, 'dashboard/change_user_data.html')

dashboard/templates/dashboard/change_user_data.html
{% extends 'core/base.html' %}

{% block title %}Змінити дані користувача{% endblock %}

{% block content %}
<div class="container mt-6">
    <div class="card p-4 bg-light rounded shadow">
        <h2 class="mb-4 text-2xl text-center">Змінити дані користувача</h2>
        <form method="post" action="{% url 'dashboard:change_user_data' %}">
            {% csrf_token %}
            <div class="mb-3">
                <label for="username" class="form-label">Нікнейм</label>
                <input type="text" class="form-control" id="username" name="username" value="{{ user.username }}" required>
            </div>
            <div class="mb-3">
                <label for="email" class="form-label">Електронна пошта</label>
                <input type="email" class="form-control" id="email" name="email" value="{{ user.email }}" required>
                {% if error_message %}
                <p class="text-danger">{{ error_message }}</p>
                {% endif %}
            </div>
            <button type="submit" class="btn btn-primary">Зберегти зміни</button>
            <button class="btn btn-danger bg-danger" onclick="window.history.back()">Скасувати</button>
        </form>
    </div>
</div>
{% endblock %}

dashboard/templates/dashboard/history.html
{% extends 'core/base.html' %}

{% block title %}Історія перегляду оголошень{% endblock %}

{% block content %}
    <div class="container mt-6">
        <div class="card p-4 bg-light rounded shadow">
            
            <h2 class="mb-1 text-2xl text-center">Переглянуті оголошення</h2>
            <div class="container mt-4">
                <div class="text-center">
                    <a href="#" onclick="window.history.back()" class="btn btn-secondary mb-4">Повернутися назад</a>
                </div>
            </div>

            <div class="row row-cols-1 row-cols-md-3 g-3">
                {% for item in items %}
                    <div class="col">
                        <a href="{% url 'item:detail' item.item.id %}">
                            <div class="card rounded-xl">
                                <img src="{{ item.item.image.url }}" class="card-img-top" alt="{{ item.name }}">
                                <div class="card-body">
                                    <h2 class="card-title text-2xl">{{ item.item.name }}</h2>
                                    <p class="card-text text-gray-500">Ціна: {{ item.item.price }}</p>
                                </div>
                            </div>
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

dashboard/templates/dashboard/index.html
{% extends 'core/base.html' %}

{% block title %}Профіль{% endblock %}

{% block content %}
    <div class="container mt-6">
        <div class="card p-4 bg-light rounded shadow">
            <div class="mb-4 text-center">
                <a href="{% url 'item:new' %}" class="btn btn-primary me-2">Створити</a>
                <a href="{% url 'dashboard:history' %}" class="btn btn-primary me-2">Історія перегляду</a>
                <a href="{% url 'dashboard:wishlist' %}" class="btn btn-primary me-2">Список обраного</a>
                <a href="{% url 'dashboard:change_user_data' %}" class="btn btn-primary me-2">Змінити дані користувача</a>
                <form method="post" class="d-inline">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger bg-danger">Вийти</button>
                </form>
            </div>
            <h2 class="mb-4 text-2xl text-center">Мої оголошення</h2>

            <div class="row row-cols-1 row-cols-md-3 g-3">
                {% for item in items %}
                    <div class="col">
                        <a href="{% url 'item:detail' item.id %}">
                            <div class="card rounded-xl">
                                <img src="{{ item.image.url }}" class="card-img-top" alt="{{ item.name }}">
                                <div class="card-body">
                                    <h2 class="card-title text-2xl">{{ item.name }}</h2>
                                    <p class="card-text text-gray-500">Ціна: {{ item.price }}</p>
                                </div>
                            </div>
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

dashboard/templates/dashboard/user_profile.html
{% extends 'core/base.html' %}

{% block title %}Оголошення користувача {{ user_profile.username }}{% endblock %}

{% block content %}
<div class="container mt-6">
    <div class="card p-4 bg-light rounded shadow">
        
        <h2 class="mb-1 text-2xl text-center">Оголошення користувача {{ user_profile.username }}</h2>
        <div class="container mt-4">
            <div class="text-center">
                <a href="#" onclick="window.history.back()" class="btn btn-secondary mb-4">Повернутися назад</a>
            </div>
        </div>

        <div class="row row-cols-1 row-cols-md-3 g-3">
            {% for item in items %}
                <div class="col">
                    <a href="{% url 'item:detail' item.id %}">
                        <div class="card rounded-xl">
                            <img src="{{ item.image.url }}" class="card-img-top" alt="{{ item.name }}">
                            <div class="card-body">
                                <h2 class="card-title text-2xl">{{ item.name }}</h2>
                                <p class="card-text text-gray-500">Ціна: {{ item.price }}</p>
                            </div>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

dashboard/templates/dashboard/wishlist.html
{% extends 'core/base.html' %}

{% block title %}Список обраного{% endblock %}

{% block content %}
    <div class="container mt-6">
        <div class="card p-4 bg-light rounded shadow">
            
            <h2 class="mb-1 text-2xl text-center">Список обраних товарів</h2>
            <div class="container mt-4">
                <div class="text-center">
                    <a href="#" onclick="window.history.back()" class="btn btn-secondary mb-4">Повернутися назад</a>
                </div>
            </div>
            
            <div class="row row-cols-1 row-cols-md-3 g-3">
                {% for item in items %}
                    <div class="col">
                        <a href="{% url 'item:detail' item.item.id %}">
                            <div class="card rounded-xl">
                                <img src="{{ item.item.image.url }}" class="card-img-top" alt="{{ item.name }}">
                                <div class="card-body">
                                    <h2 class="card-title text-2xl">{{ item.item.name }}</h2>
                                    <p class="card-text text-gray-500">Ціна: {{ item.item.price }}</p>
                                    <div class="d-flex justify-content-end mt-2">
                                        <form method="post" action="{% url 'dashboard:remove_from_wishlist2' item.item.id %}">
                                            {% csrf_token %}
                                            <button type="submit" class="btn btn-danger">Видалити</button>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}